# Copiez ce contenu tel quel (UTF-8 sans BOM, espaces uniquement, pas de tabulations)
version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: "appdb"
      MYSQL_USER: "${DB_USER}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  backend:
    build: ./backend
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_NAME: "appdb"
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      ADMIN_EMAIL: "${ADMIN_EMAIL}"
      ADMIN_PASSWORD: "${ADMIN_PASSWORD}"
    depends_on:
      - db
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    environment:
      REACT_APP_API_URL: "http://localhost:5000"
    ports:
      - "3000:3000"

volumes:
  db_data: